os: osx
osx_image: xcode9.3beta
language: c # or other C/C++ variants
cache: ccache

before_install:
  - mkdir -p ~/.local/bin
  - mkdir ~/junit
  - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
  - brew install gnu-sed coreutils ccache e2fsprogs
  - pip install --user yamlish junit_xml
  - ln -sf /usr/local/bin/gsed ~/.local/bin/sed
  - ln -sf /usr/local/bin/gdate ~/.local/bin/date
  - ln -sf /usr/local/opt/e2fsprogs/sbin/mkfs.ext4 ~/.local/bin/

script:
  - cp tools/lkl/bin/x86_64-apple-darwin17.4.0-objcopy ~/.local/bin/objcopy
  - make -C tools/lkl
  - make -C tools/lkl run-tests tests="--junit-dir ~/junit"
